version: '3'
services:
  db:
    image: postgres
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  sftp:
    build: .
    expose:
      - 2022
      - 8080
    volumes:
    - ./srv/sftpgo/data:/app/data
    - ./srv/sftpgo/config:/app/config
    - ./srv/sftpgo/backup:/app/backup
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sftp
    ports:
      - "8080:8080"
      - "22:22"